---
name: Generate Weekly Issue

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Generate issue
    runs-on: ubuntu-latest
    steps:
      - name: Generate issue
        uses: garnertb/weekly-issue-action@master
        with: 
          date-string: "this friday"
          body: Weekly sync body
          token: ${{ secrets.github_token }}

      
